server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: video/mpeg4-generic, video/mpeg, video/mp4, video/ogg, video/3gpp, video/x-matroska
    ffmpeg: ${FFMPEG_PATH:ffmpeg}
    ffprobe: ${FFPROBE_PATH:ffprobe}
spring:
  application:
    name: uploader
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:uploader}
    username: ${POSTGRESQL_USERNAME:uploader}
    password: ${POSTGRESQL_PASSWORD:uploader}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    check-location: true
    clean-disabled: false
    clean-on-validation-error: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 200MB
      max-file-size: 200MB
  mvc:
    dispatch-options-request: true
